name: CD - Deploiement Automatique

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Construire l'image Docker
        run: docker build -t monapp:latest .

      - name: Se connecter au serveur et déployer
        uses: appleboy/ssh-action@v0.1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          username: ${{ secrets.SERVER_USER }}
          script: |
            docker stop monapp || true
            docker rm monapp || true
            docker run -d -p 80:80 --name monapp monapp:latest